### ISSUE TITLE
Modify get/all endpoint to conform query format for Dune

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-leaderboard#138]
### Is your feature related to a problem?

The `/api/get/all` endpoint right now only showcases all the existing `streamId`s related to the HOPR nodes, but is unable to be parsed into a format Dune can actually process cc @QYuQianchen 

### Describe the feature you'd like

Create `/api/get/dune/all` which produces the output needed to be parsed by Dune.

### Describe alternatives you've considered

Due to the amount of data processing required, we might need to offload this data to another server or endpoint.

### Additional context

We need input from @QYuQianchen on the schema (format) needed for Dune. It was previously shared in our internal chat but it would be good to have it documented.

**Comment by QYuQianchen** [comment]
The endpoint should return
```ts
{
   ethAddressString: string,
   nodeAddressString: string
}[]
```

1. For values of `ethAddressString`:
    1. each string includes no more than <strong>186</strong> ethereum addresses (of length `7997`), because Dune cannot handle too big data upload at once)
    2. addresses are separated by `,` but no ` `  (space)
    3. No `[` or `]`
    4. Ideally all small caps.
    example value of `ethAddressString`: `'0x26497c3e8dfc161ef7c5301be2bdc123717c45ca,0xf2d3712102001c2d7c2fec82227364b615199088,0xd3691bf3184b3b3a4808b652cd7b77512446ccac'`
2. `nodeAddressString`has the ethereum-like `correspondingHoprNode`address, whose format also follows above-mentioned `1.i)`, `1.ii)`, `1.iii)` and `1.iv)`

**Comment by QYuQianchen** [comment]
FYI, as pointed by @robertkiel. To convert node address to ethereum address.
```js
import PeerId from 'peer-id'
import { PublicKey } from '@hoprnet/hopr-utils'

PublicKey.fromPeerId(PeerId.fromB58String(<hoprdId>)).toAddress()
```

**Comment by QYuQianchen** [comment]
What would be even more lovely is to have an endpoint, like `/api/get/dune/parsed`:
```js
const resultFromAPI = []; // the array returned from `/api/get/dune/all`
const sqlBlock = (obj) => `SELECT decode(lower(substring(unnest(regexp_split_to_array('`${obj.ethAddressString}`', ',')), 3)), 'hex')::bytea AS eoa, decode(lower(substring(unnest(regexp_split_to_array('`${obj.nodeAddressString}`', ',')), 3)), 'hex')::bytea AS node`
const parsed = resultFromAPI.reduce((acc, cur, index) => index === 0 ? sqlBlock(cur) : acc + ' UNION ALL ' + sqlBlock(cur), '');
```
When the array returned from `/api/get/dune/all` is of length 3, it looks like:

![image](https://user-images.githubusercontent.com/10935300/132667860-f47036fc-05fd-4300-aca6-914c326ebedd.png)
