### ISSUE TITLE
leaderboard UX changes & polishing

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-leaderboard#20]
Some small changes on leaderboard frontend:

- [x] add HOPR logo favicon
- [x] HOPR icon in top left should link to website hoprnet.org
- [x] change all Ethereum addresses to links like https://explorer.matic.network/address/0x4774fEd3f2838f504006BE53155cA9cbDDEe9f0c
- [x] let me copy paste HOPR and Ethereum addresses from table even though they are cropped in UI
- [x] remove `tweetid` from table
- [x] make table sortable by headers (by default should be sorted by score)
- [x] replace `TOP ASSETS` by `HOPR ALLOCATION` that shows the same table as on the blog (but in HTML): https://medium.com/hoprnet/hopr-bas%C3%B2dino-a-better-bigger-braver-testnet-97f68e1c9b7e
- [x] in `Instructions` replace the Twitter logo + hashtag by `click here to tweet` link
- [x] under the table with instructions leave again a message "If you encountered any issues please let us know on Discord[link] or Telegram[link]
- [x] change the stats on the bottom right that currently shows `1 Available` etc which is not very meaningful to: HOPR token address, HOPR payment channel address only (linked to blockchain explorer)
- [x] On top right under `Welcome to HOPR Basòdino testnet` add a link to our medium post linked above.

----

- [x] On the top-right, change "follow us on [medium] medium." to "Follow us on [medium] medium."
- [x] Refresh button doesn't work
- [ ] https://github.com/hoprnet/hoprnet/issues/395

**Comment by ilodi** [comment]
> Some small changes on leaderboard frontend:
> 
> * [x]  add HOPR logo favicon
> * [x]  HOPR icon in top left should link to website hoprnet.org
> * [x]  change all Ethereum addresses to links like https://explorer.matic.network/address/0x4774fEd3f2838f504006BE53155cA9cbDDEe9f0c
> * [x]  let me copy paste HOPR and Ethereum addresses from table even though they are cropped in UI
> * [x]  remove `tweetid` from table
> * [x]  make table sortable by headers (by default should be sorted by score)
> * [x ]  replace `TOP ASSETS` by `HOPR ALLOCATION` that shows the same table as on the blog (but in HTML): https://medium.com/hoprnet/hopr-bas%C3%B2dino-a-better-bigger-braver-testnet-97f68e1c9b7e
> * [x]  in `Instructions` replace the Twitter logo + hashtag by `click here to tweet` link
> * [x]  under the table with instructions leave again a message "If you encountered any issues please let us know on Discord[link] or Telegram[link]
> * [ x]  change the stats on the bottom right that currently shows `1 Available` etc which is not very meaningful to: HOPR token address, HOPR payment channel address only (linked to blockchain explorer)
> * [x]  On top right under `Welcome to HOPR Basòdino testnet` add a link to our medium post linked above.
> 
> * [x]  On the top-right, change "follow us on [medium] medium." to "Follow us on [medium] medium."
> * [x]  Refresh button doesn't work
> * [ ]  https://github.com/hoprnet/hoprnet/issues/395

**Comment by nionis** [comment]
Closing this issue as all items are complete except #21 which has its own issue.
