### ISSUE TITLE
Leaderboard table shows all nodes are online

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-leaderboard#21]
## Expected Behavior

It should show offline nodes

## Current Behavior

Shows all nodes as online

**Comment by ilodi** [comment]
According to the standard to know if they are online or not. it is only knowing if there is an address.
Do you have any ideas or ways to make this process better. Or where I can take this data in a better way
![Uploading Screen Shot 2020-10-28 at 11.26.16.png…]()

**Comment by ilodi** [comment]
![Screen Shot 2020-10-28 at 11 26 16](https://user-images.githubusercontent.com/18120638/97473436-97177480-1910-11eb-9fa0-f98125eb2cf0.png)

**Comment by nionis** [comment]
@jjperezaguinaga looks like that `state.connected` results to the verified nodes instead of the connected ones -> [coverbot](https://github.com/hoprnet/hoprnet/blob/77cd704b678e8fd6dd1d478584f2648a2f56d922/packages/chatbot/src/bots/coverbot/index.ts#L152-L171).

@ilodi can you try using `state.connectedNodes` instead?
https://github.com/hoprnet/hopr-leaderboard/blob/1e71bfde8747a0d592ddc0c1d4d9cbab8488aaa6/utils/api.js#L32

**Comment by jjperezaguinaga** [comment]
Added `needs review` label as this one still needs a proper API to showcase this information.
