### ISSUE TITLE
Change "copy to clipboard" behaviour

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-leaderboard#22]
### Is your feature related to a problem?

I am not a big fan of the current behaviour, I don't see the need to open a popup.

### Describe the feature you'd like

A simple tooltip like "copied to clipboard" is sufficient IMO.

**Comment by jjperezaguinaga** [comment]
New behaviour has been implemented and confirmed to be available in at least 3187065 (was implemented before).
