### ISSUE TITLE
Bot addresses are hardcoded

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-leaderboard#25]
## Expected Behavior

Coverbot address is being retrieved from the database.

## Current Behavior

Coverbot addresses are hardcoded in `layout.js` and `help.js`

## (Optional) Possible Solution

Just fetch the bot address from the API

## Steps to Reproduce

1. See `layout.js`
2. See `help.js`

**Comment by betinho89** [comment]
It's done here 8ba3210810185d60eb320bf3d38e5483bca5c7fd
