### ISSUE TITLE
Provide the address of the node currently in a given rank in the allocation section

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-leaderboard#26]
### Is your feature related to a problem?

Right now it's not easy to answer the question "in which rank am I", I first need to sort by score or find me, and count whether I'm at a given rank.

### Describe the feature you'd like

It would be great to have an additional column in the `hopr-allocation` section that has the address of the user at that rank.

(see poor example)

![image](https://user-images.githubusercontent.com/1128312/97669520-93a4fa00-1a84-11eb-89ec-79903a31d034.png)

### Describe alternatives you've considered

We used to have this before (with even a nice prize icon!). Let's bring that back, even if it's just only the ones that have from `1` address. We'll figure something out for the `11-20` rank and the following one.

### Additional context

Some users were complaining that it wasn't really easy for them to know whether they will earn a prize or not

**Comment by jjperezaguinaga** [comment]
@thewanderingeditor @kitschbent I believe we already have the way the community decided to implement this breakdown, could you share it here?

**Comment by kitschbent** [comment]
@jjperezaguinaga I believe this is the info you're needing (generated from our community input form)

Summary:

- 250 ranked prizes

- Top prize of 6000 

- 25 random prizes of 800 each

![Screen Shot 2020-11-24 at 9.05.55 PM.png](https://images.zenhubusercontent.com/5fae783cad9b1d12a482cf41/7b5c76f1-244a-4921-b1fd-446bbed90ac5)
