### ISSUE TITLE
Sort by score as a default view for home

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-leaderboard#27]
### Is your feature related to a problem?

People want to see their nodes and scores. We are asking them to do an extra click which shouldn't be needed.

### Describe the feature you'd like

Ensure `score` is always the default view on `/home`

### Describe alternatives you've considered

Right now we have `onClickColumn` or something like that. We can easily have it inside an `useEffect` and/or `await` for `setData`. Beware, doing `useEffect(() => onClickSort('score'), [data]` will make the table switch `score` all the time due the other `useEffect` in the component.

### Additional context

The `onClickColumn` sort has a bunch of `aNew` and `sSort` variables. If we can also use better namings that would be great.

**Comment by betinho89** [comment]
It's done, you can see here 55e4d63bf2fceba25e72931af6941f37daca0683
