### ISSUE TITLE
Showcase coverbot health status

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-leaderboard#29]
### Is your feature related to a problem?

Sometimes the bot will be down and it is not clear to the users whether that is the case.

### Describe the feature you'd like

Showcase something in the leaderboard that shows whether the bot is alive or not.

### Describe alternatives you've considered

Let's use an API that can ping our bot in the node port to showcase if its alive or not. Additionally, setup a cronjob instead that runs X amount of time and spins a HOPR node that pings the `coverbot`.

### Additional context

Users want to know when to ping the team if the bot is down and/or whether or not the bot is working.

**Comment by nionis** [comment]
@jjperezaguinaga can u "draw" how it would work like: x -> y -> z? because I am not sure where the API is a such

**Comment by jjperezaguinaga** [comment]
We ended up removing this one, so closing it for now.
