### ISSUE TITLE
Showcase a group chat for users to interact with

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-leaderboard#31]
### Is your feature related to a problem?

No, just a feature really.

### Describe the feature you'd like

It would be nice to have a chat-like feature where users could connect their nodes to and send/read messages from a coverbot-group like.

### Describe alternatives you've considered

We have a web-app demo (https://github.com/hoprnet/hopr-webapp-demo) that has shown this, but unfortunately, we don't have an easy way to ship the server to our new users. Even worse, the server is deprecated.

### Additional context

@nionis This is blocked in many ways but wanted to keep it on the record. The needed steps are,

1. Create a web-socket like a server exposable via some REST-like interface
2. Create a distributable version of HOPR that can ship this interface
3. Encourage users to download and run this version
4. Update the leaderboard to allow connection with a user node via the REST API
5. Provide an interface that can interact with the node a-la chat
6. Deploy a new version of coverbot that only listens to chat messages and/or deploy a custom service just this
7. Update the leaderboard to use this interface and be able to chat to this coverbot-chat service.

**Comment by nionis** [comment]
@jjperezaguinaga to me it makes sense to update `hopr-server` into having the capability to use `ws` / `http`, while using only one source of truth, example:

```
(protos -> js methods) <-> transfer protocol
```

due to the nature of `nestjs` we can achieve this and deprecate `grpc` but reuse that codebase, in the future, if we ever need `grpc` again, we can restore it

**Comment by jjperezaguinaga** [comment]
Definitely want to restart that conversation for `zug`
