### ISSUE TITLE
The mobile terminal cannot download the node ranking file

### ISSUE THREAD

**Issue by bananooo-zhang** [hoprnet/hopr-leaderboard#45]
## Expected Behavior

Download csv file on mobile

## Current Behavior

Cannot download csv file on mobile

## (Optional) Possible Solution

(Write your answer here.)

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

(Write your answer here.)

## Detailed Description

xiaomi10pro
os 12.0.1

## Logs

(Write your answer here.)

## (Optional) Possible Implementation

(Write your answer here.)

**Comment by nionis** [comment]
@jjperezaguinaga not familiar with the android platform, but I guess you can download files as you do on desktop right?

**Comment by bananooo-zhang** [comment]
the pc cant open refresh&nbsp;
waiting long time

---Original---

**Comment by jjperezaguinaga** [comment]
@betinho89 can you take a look at this one?
