### ISSUE TITLE
Update all content in the site to match Wildhorn

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-leaderboard#63]

**Comment by thewanderingeditor** [comment]
Some stuff here that looks like it needs changing prior to the 4pm announcement drop.

From what I can see:

**Text at the top right:**

"Welcome to HOPR Wildhorn Testnet!" currently has a link to an old Basodino blog. For now I think that needs to just be deleted.
Let's change "There is series of NFTs for people and high score earners based on their HOPR nodes activities." just below that to "Earn HOPR boost NFTs based on your node activity."

**Network Page:**

No changes, although if it's easy I'd either remove the score column or replace the whole panel with some placeholder text like "After launch, this panel will show the status of nodes in the HOPR network, along with their current score"

**NFTs:**

I guess this whole thing needs to be placeholdered for now? Suggested text: "After launch, this panel will show the top NFT earners and instructions on how to claim your NFT."

**Node(s):**

This all seems fine. It's just whether you want people to start funding and using their nodes right away. Maybe needs a caveat explaining you can't get points yet, but feel free to fund and play around?

**Help:**

As above. Looks good, maybe needs a caveat that no points will be accrued until Thursday?
