### ISSUE TITLE
Requesting funds for a second node fails

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-leaderboard#89]
## Expected Behavior

Ideally, when requesting funds for a second node, the second node is also funded even if a previously node fund was requested.

## Current Behavior

When people try to fund a second node they get `REQUESTOR HAS MATIC TO FUND NODES`.

## (Optional) Possible Solution

Remove check on the requestor.

## Steps to Reproduce

1. Request funds with account `0x9d57f5a26E3112406c80334058dF7390A9ABDD7A` for node `16Uiu2HAmLjY9r2bUbHD75uRUezgUS9gKo8yupLJoFrAPUUyE5XR5`
2.  Get `REQUESTOR HAS MATIC TO FUND NODES` and get no funds.

## Context (Environment)

This occurs in the latest version of leaderboard.

## Detailed Description

No information was provided.

## (Optional) Possible Implementation

Instead of checking whether the requestor has funds, we can check whether they have at least 0.01291.

**Comment by iranzo** [comment]
The message received now lists that it sent two different funds,but nothing happened since this morning and matic dind't arrive.

repeating the procedure, now reports that node already has matic but node hasn't started and metamask doesn't show any amount other than 0.00
