### ISSUE TITLE
Funding second node gives an error

### ISSUE THREAD

**Issue by Jaguaras** [hoprnet/hopr-leaderboard#97]
## Expected Behavior

Adding 2nd node address into the field and trying to get funds, it should transfer 0.01 Matic & some mHOPR tokens. 

## Current Behavior

Adding 2nd node address into the field and trying to get funds, after clicking on the button 'fund' and signing with metamask it brings error message: `An unexpected error has occurred.`

## Steps to Reproduce

1. Fund 1st node by entering node address & sign with metamask
2. Fund 2nd node by entering node address & sign with metamask

## Context (Environment)

1st node I funded without any issues. With the 2nd node I wasn't able to fund.

## Screenshot

(Write your answer here.)

![image](https://user-images.githubusercontent.com/73285987/131187791-a7639ad1-83ac-45ee-9c9c-cc90e93d7619.png)

**Comment by jjperezaguinaga** [comment]
Sounds like a duplicate from #96, closing this one, please subscribe to that one.
