### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by jekan323** [hoprnet/hopr-leaderboard#98]
## Expected Behavior

Funding the Node

## Current Behavior

When using the button Fund, I am getting this error:

An unexpected error has occurred.

## (Optional) Possible Solution

(Write your answer here.)

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

(Write your answer here.)

## Detailed Description

(Write your answer here.)

## Logs

(Write your answer here.)

## (Optional) Possible Implementation

(Write your answer here.)

**Comment by Jaguaras** [comment]
@jekan323 Please update your issue with more details:
- Screenshot of browsers console (when you are trying to fund)
- Matic & mHOPR balance on your wallet & node

**Comment by jjperezaguinaga** [comment]
Sounds similar to #96, closing this one to favor that one. Please subscribe to #98 for updates.
